title = "EH Study"
paginate = 5
theme = "charlolamode"
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[[menu.main]]
name = "Classes"
url = "classes/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 20

[params]
# author = "Author's Name"
defaultTheme = "auto"
# ShowShareButtons = true
ShowReadingTime = false
displayFullLangName = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
mainSections = [ "articles" ]

  [params.profileMode]
  enabled = true
  title = "What is this?"
  description = """

A resources hub for students and teachers at English House ⸜(｡˃ ᵕ ˂ )⸝


"""
  imageUrl = "/images/profile.png"
  imageTitle = "cat"

  # [[params.socialIcons]]
  # name = "buymeacoffee"
  # url = "https://ko-fi.com/heycharlola"

  # [[params.socialIcons]]
  # name = "github"
  # url = "https://github.com/charlola"

  # [[params.socialIcons]]
  # name = "linkedin"
  # url = "https://www.linkedin.com/in/heycharlola/"

  [params.assets]
  favicon = "/images/favicon.ico"
  favicon16x16 = "/images/favicon-16x16.png"
  favicon32x32 = "/images/favicon-32x32.png"
  apple_touch_icon = "/images/apple-touch-icon.png"
  safari_pinned_tab = "/images/apple-touch-icon.png"

[minify]
disableXML = true
